### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by Atul9** [comment]
Hi @fubuloubu I have fixed the merge conflict. Is there any plan to merge this PR?

**Comment by fubuloubu** [comment]
sorry! I must have missed when you originally posted this!

**Comment by Atul9** [comment]
@fubuloubu its ok, Can you please suggest any good-first-issue which I can look into in this/any other repo of zatoichi-labs or any of your open source project?

**Comment by fubuloubu** [comment]
Not off the top of my head, but feel free to play around with this project and see if there's areas for improvement.

**Pull request merged**
